### PR TITLE
add a post plot script

### PR DESCRIPTION
**Pull request by xqp**
i would like to add my post plot hook.

with this its easy to transferthe plot with scp to a remote host

### CODE REVIEW

**Comment by swar** [comment]
@xqp I see what you are doing and I see it's helpfulness as well. Can you merge conflicts with the development branch and I can take a look at this tomorrow?

**Comment by FilixDark** [comment]
@xqp thx for that, exactly what I had in mind, good I checked the pull requests before getting my hands dirty.

**Comment by tandyuk** [comment]
Check out https://github.com/tandyuk/Swar-Chia-Plot-Manager/commit/820a80b9724ab14d864eaa42c459121146ea15e2  for a couple of missing references to post_plot_script

Not sure how to do it properly with github lol

**Comment by xqp** [comment]
@tandyuk can u create a PR for this? i would merge this into this PR :D

**Comment by maxcom99** [comment]
Can this please be merged?

**Pull request closed without merging**
