### PR TITLE
Added global "minutes_between_jobs" setting

### PR DESCRIPTION
**Pull request by Berni8k**
Introduces a way to easily stagger the starting of multiple jobs. Once a job starts then globaly no new jobs are allowed to start for this amount of time.

### CODE REVIEW

**Comment by swar** [comment]
I will be tweaking this up a bit to get it implemented. Thank you for not only suggesting a new feature but actually implementing yourself. +1

**Comment by Berni8k** [comment]
No problem. I implemented it mostly to get my chia plotting rig to work the way i want. I have it rnning for some time now and it is great. Plotting on multiple drives is a nightmare without it. Thanks for sharing it.

In terms of features, it would be nice if the output of this job creation function was made visible in the console GUI, giving the user some imediate feedback for reason behind not starting the next job yet. Such as each job having an additional status column that says things such as "Max concurrent plots" "Max phase 1 plots" "Max global plots". So far you only see this in the INFO debug log, but is a great tool for figuring out what setting in the config.yaml the manager is waiting for. Not a feature i need since i have the config figured out, but might help new users and reduce the questions from confused users.

**Comment by StormYudi** [comment]
That's great! Thank you for your work.

**Comment by alexhu98** [comment]
Works great. Thanks Berni8k.

**Comment by swar** [comment]
Adding this to temp branch before merging with development branch.

**Pull request merged**
