### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by laroyru**

### CODE REVIEW

**Comment by swar** [comment]
What is this... did you read the readme? There's two different requirements so people don't have to download the notification requirements.

**Comment by laroyru** [comment]
Oh, I was looking to the main branch. Adding dateutils and wheel to the requirements fixed my installation issues on Ubuntu.

**Comment by swar** [comment]
How did you identify the issues? I'm curious because I haven't see anyone else having these kinds of issues yet.

**Comment by hieunguyenmsft** [comment]
I had a similar problem (checked out the main branch). When ran  `python manager.py start` I saw errors like:`ModuleNotFoundError: No module named 'dateparser'` and I just manually install the missing packages. It's on a branch new machine. I need to install pyyaml, psutil, dateparser, pushover, playsound, discord something.

**Comment by swar** [comment]
> I had a similar problem (checked out the main branch). When ran `python manager.py start` I saw errors like:`ModuleNotFoundError: No module named 'dateparser'` and I just manually install the missing packages. It's on a branch new machine. I need to install pyyaml, psutil, dateparser, pushover, playsound, discord something.

These should already be in the default requirements.txt

**Comment by laroyru** [comment]
> How did you identify the issues? I'm curious because I haven't see anyone else having these kinds of issues yet.
Here's a clean install log. So wheel is clearly an issue missing from the requirements. However no issues with dateutils this time, perhaps due to using python3 and pip3 commands instead of python and pip like the installation guide suggests.

farmer@cz7376:~$ git clone https://github.com/swar/Swar-Chia-Plot-Manager.git
Cloning into 'Swar-Chia-Plot-Manager'...
remote: Enumerating objects: 1773, done.
remote: Counting objects: 100% (811/811), done.
remote: Compressing objects: 100% (376/376), done.
remote: Total 1773 (delta 535), reused 610 (delta 428), pack-reused 962
Receiving objects: 100% (1773/1773), 328.00 KiB | 4.75 MiB/s, done.
Resolving deltas: 100% (1097/1097), done.
farmer@cz7376:~$ cd Swar-Chia-Plot-Manager/
farmer@cz7376:~/Swar-Chia-Plot-Manager$ python3 -m venv venv
farmer@cz7376:~/Swar-Chia-Plot-Manager$ . ./venv/bin/activate
(venv) farmer@cz7376:~/Swar-Chia-Plot-Manager$ pip3 install -r requirements.txt
Collecting dateparser==1.0.0
  Downloading dateparser-1.0.0-py2.py3-none-any.whl (279 kB)
     |████████████████████████████████| 279 kB 5.2 MB/s
Collecting discord_notify==1.0.0
  Downloading discord_notify-1.0.0-py3-none-any.whl (4.3 kB)
Collecting playsound==1.2.2
  Downloading playsound-1.2.2-py2.py3-none-any.whl (6.0 kB)
Collecting psutil==5.8.0
  Downloading psutil-5.8.0-cp38-cp38-manylinux2010_x86_64.whl (296 kB)
     |████████████████████████████████| 296 kB 8.1 MB/s
Collecting python_pushover==0.4
  Downloading python-pushover-0.4.tar.gz (19 kB)
Collecting PyYAML==5.4.1
  Using cached PyYAML-5.4.1-cp38-cp38-manylinux1_x86_64.whl (662 kB)
Collecting python-dateutil
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting tzlocal
  Downloading tzlocal-2.1-py2.py3-none-any.whl (16 kB)
Collecting pytz
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 9.3 MB/s
Collecting regex!=2019.02.19
  Downloading regex-2021.4.4-cp38-cp38-manylinux2014_x86_64.whl (733 kB)
     |████████████████████████████████| 733 kB 11.3 MB/s
Collecting requests>=1.0
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 9.7 MB/s
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 11.6 MB/s
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
     |████████████████████████████████| 153 kB 11.4 MB/s
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 8.9 MB/s
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 10.8 MB/s
Building wheels for collected packages: python-pushover
  Building wheel for python-pushover (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/farmer/Swar-Chia-Plot-Manager/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w1kgxe6k/python-pushover/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w1kgxe6k/python-pushover/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-xkg4lk4x
       cwd: /tmp/pip-install-w1kgxe6k/python-pushover/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for python-pushover
  Running setup.py clean for python-pushover
Failed to build python-pushover
Installing collected packages: six, python-dateutil, pytz, tzlocal, regex, dateparser, discord-notify, playsound, psutil, chardet, urllib3, idna, certifi, requests, python-pushover, PyYAML
    Running setup.py install for python-pushover ... done
Successfully installed PyYAML-5.4.1 certifi-2020.12.5 chardet-4.0.0 dateparser-1.0.0 discord-notify-1.0.0 idna-2.10 playsound-1.2.2 psutil-5.8.0 python-dateutil-2.8.1 python-pushover-0.4 pytz-2021.1 regex-2021.4.4 requests-2.25.1 six-1.16.0 tzlocal-2.1 urllib3-1.26.4
(venv) farmer@cz7376:~/Swar-Chia-Plot-Manager$ pip3 install wheel
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel
Successfully installed wheel-0.36.2
(venv) farmer@cz7376:~/Swar-Chia-Plot-Manager$ pip3 install -r requirements.txt
Requirement already satisfied: dateparser==1.0.0 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.0.0)
Requirement already satisfied: discord_notify==1.0.0 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (1.0.0)
Requirement already satisfied: playsound==1.2.2 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (1.2.2)
Requirement already satisfied: psutil==5.8.0 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (5.8.0)
Requirement already satisfied: python_pushover==0.4 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (0.4)
Requirement already satisfied: PyYAML==5.4.1 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (5.4.1)
Requirement already satisfied: python-dateutil in ./venv/lib/python3.8/site-packages (from dateparser==1.0.0->-r requirements.txt (line 1)) (2.8.1)
Requirement already satisfied: pytz in ./venv/lib/python3.8/site-packages (from dateparser==1.0.0->-r requirements.txt (line 1)) (2021.1)
Requirement already satisfied: regex!=2019.02.19 in ./venv/lib/python3.8/site-packages (from dateparser==1.0.0->-r requirements.txt (line 1)) (2021.4.4)
Requirement already satisfied: tzlocal in ./venv/lib/python3.8/site-packages (from dateparser==1.0.0->-r requirements.txt (line 1)) (2.1)
Requirement already satisfied: requests>=1.0 in ./venv/lib/python3.8/site-packages (from python_pushover==0.4->-r requirements.txt (line 5)) (2.25.1)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.8/site-packages (from python-dateutil->dateparser==1.0.0->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: idna<3,>=2.5 in ./venv/lib/python3.8/site-packages (from requests>=1.0->python_pushover==0.4->-r requirements.txt (line 5)) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in ./venv/lib/python3.8/site-packages (from requests>=1.0->python_pushover==0.4->-r requirements.txt (line 5)) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.8/site-packages (from requests>=1.0->python_pushover==0.4->-r requirements.txt (line 5)) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venv/lib/python3.8/site-packages (from requests>=1.0->python_pushover==0.4->-r requirements.txt (line 5)) (1.26.4)

**Comment by sothix** [comment]
The error "No module named dateparser" usually happens if you forget to venv/bin/activate.

**Comment by jack60612** [comment]
@laroyru please close this pull request as the issue was solved

**Pull request closed without merging**
