### PR TITLE
Add support for instrumentation using Prometheus

### PR DESCRIPTION
**Pull request by swar**
This is an extension of #87

### CODE REVIEW

**Comment by swar** [comment]
@tgxiii 

Can you confirm to me that this branch works for you with Prometheus?

**Comment by tgxiii** [comment]
Getting an error:

```
Traceback (most recent call last):
  File "C:\Chia\Swar-Chia-Plot-Manager\manager.py", line 36, in <module>
    view()
  File "C:\Chia\Swar-Chia-Plot-Manager\plotmanager\library\utilities\commands.py", line 109, in view
    jobs, running_work = get_running_plots(jobs=jobs, running_work=running_work,
  File "C:\Chia\Swar-Chia-Plot-Manager\plotmanager\library\utilities\processes.py", line 260, in get_running_plots
    set_plots_running(total_running_plots=assumed_job.total_running, job_name=assumed_job.name,
  File "C:\Chia\Swar-Chia-Plot-Manager\plotmanager\library\utilities\instrumentation.py", line 19, in set_plots_running
    gauge_plots_running, counter_plots_completed = _get_metrics(instrumentation_settings)
  File "C:\Chia\Swar-Chia-Plot-Manager\plotmanager\library\utilities\instrumentation.py", line 10, in _get_metrics
    gauge_plots_running = Gauge('chia_running_plots', 'Number of running plots', ['hostname', 'queue'])
  File "C:\Python39\lib\site-packages\prometheus_client\metrics.py", line 336, in __init__
    super(Gauge, self).__init__(
  File "C:\Python39\lib\site-packages\prometheus_client\metrics.py", line 121, in __init__
    registry.register(self)
  File "C:\Python39\lib\site-packages\prometheus_client\registry.py", line 29, in register
    raise ValueError(
ValueError: Duplicated timeseries in CollectorRegistry: {'chia_running_plots'}
```

**Comment by tgxiii** [comment]
I'll debug tomorrow, but I think it might be because `_get_metrics` is getting called more than once.

**Comment by swar** [comment]
> Getting an error:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Chia\Swar-Chia-Plot-Manager\manager.py", line 36, in <module>
>     view()
>   File "C:\Chia\Swar-Chia-Plot-Manager\plotmanager\library\utilities\commands.py", line 109, in view
>     jobs, running_work = get_running_plots(jobs=jobs, running_work=running_work,
>   File "C:\Chia\Swar-Chia-Plot-Manager\plotmanager\library\utilities\processes.py", line 260, in get_running_plots
>     set_plots_running(total_running_plots=assumed_job.total_running, job_name=assumed_job.name,
>   File "C:\Chia\Swar-Chia-Plot-Manager\plotmanager\library\utilities\instrumentation.py", line 19, in set_plots_running
>     gauge_plots_running, counter_plots_completed = _get_metrics(instrumentation_settings)
>   File "C:\Chia\Swar-Chia-Plot-Manager\plotmanager\library\utilities\instrumentation.py", line 10, in _get_metrics
>     gauge_plots_running = Gauge('chia_running_plots', 'Number of running plots', ['hostname', 'queue'])
>   File "C:\Python39\lib\site-packages\prometheus_client\metrics.py", line 336, in __init__
>     super(Gauge, self).__init__(
>   File "C:\Python39\lib\site-packages\prometheus_client\metrics.py", line 121, in __init__
>     registry.register(self)
>   File "C:\Python39\lib\site-packages\prometheus_client\registry.py", line 29, in register
>     raise ValueError(
> ValueError: Duplicated timeseries in CollectorRegistry: {'chia_running_plots'}
> ```

And to confirm this wasn't happening in your original branch? Weird... I need to figure out how to setup Prometheus to test this out in this case. It was working for me but I also have no server setup. Could this be because view and manager are two processes running and calling both methods?

**Comment by swar** [comment]
> I'll debug tomorrow, but I think it might be because `_get_metrics` is getting called more than once.

That makes sense to me. I just wanted to nest these in the appropriate methods... now I see why you had it like that. I will take more of a look at it tomorrow as well.

**Comment by swar** [comment]
@tgxiii  I think I have changes that fixed whatever I did on Sunday :)

**Pull request merged**
