### PR TITLE
Add plot process cpu affinity (psutil)

### PR DESCRIPTION
**Pull request by jjexpat00**
This implementation of [`psutil.Process().cpu_affinity()`](https://psutil.readthedocs.io/en/latest/#psutil.Process.cpu_affinity
) lets the user parameterize a selection of cores/threads specific to their plotting system and bind configured CPU affinity for newly created plotting processes. As specified in the readme and `config.yaml` documentation, this functionality gives the user greater control over their plotting machine's resources.

Some users run full node, wallet, and harvester in addition to plotting processes - I have personally experienced and have seen others run into issues when CPU resource allocation is fully consumed by plotting processes. Even on high-end multi-core CPU's, this may lead to node de-sync and delayed plot scanning (to name a few).

Enabling CPU core/thread restrictions will objectively decrease plotting speed, making this feature optional and disabled by default.

Let me know if there are better formatting conventions and logic simplification.

Any suggestions are welcome.

### CODE REVIEW

**Comment by trekb** [comment]
Onother way of acomplish the same goal is to define the process priority. If the plotter process is launched with LOW priority, the system behaviour will be much better, while potentially still using all the available resources for plotting.

**Comment by feldsam** [comment]
@trekb , there is already renice to priority 10 on linux machines and some "normal" priority on windows machines.

**Comment by feldsam** [comment]
@stubmirror contributions are welcome ;)

**Comment by swar** [comment]
I want to add this to the development branch but with the amount of questions I have been getting lately, I need to find a way to make it so people don't start complaining why their plots are going slow and then realizing they used this functionality wrong. Will keep this open. I made a branch to merge my current changes with it as well.

**Comment by swar** [comment]
https://github.com/swar/Swar-Chia-Plot-Manager/tree/jjexpat00-psutil-plot-process-affinity

**Comment by swar** [comment]
okay moved it to job level instead of global. should be good to go esp since its default set to false

**Comment by MMJ997** [comment]
> https://github.com/swar/Swar-Chia-Plot-Manager/tree/jjexpat00-psutil-plot-process-affinity
Two CPUs will have an error. 

enable_cpu_affinity: false is also useless, the software will only call CPU0, not CPU1. 
微信图片_20210609123722
微信图片_202106091237221
微信图片_202106091237222

**Pull request closed without merging**
