### PR TITLE
Skip 'manager.log' when getting log file path 

### PR DESCRIPTION
**Pull request by ianmktu**
The view pipeline would sometimes use 'manager.log' as the log file path for a plot, so sometimes plot info would not update correctly.

This proposed change skips the 'manager.log' file.

### CODE REVIEW

**Comment by swar** [comment]
Ahhh I've never seen this happen before, will add this in later tonight

**Comment by swar** [comment]
@ianmktu  with the newest version of the code, does this still happen for you? I am trying to figure out why this would end up happening to see if I can fix a bigger issue at hand.

**Comment by ianmktu** [comment]
Yes, it still happens with the latest version.

In the for loop if it encounters `manager.log` first it breaks, as a result it doesn't reach the correct log file for the plot process.

**Comment by ianmktu** [comment]
See if I do print outs like below - removing the `break` so it views the entire list:

```
            print("\n-------")
            for index, file in enumerate(process.open_files()):                
                if '.mui' == file.path[-4:]:
                    continue
                if file.path[-4:] not in ['.log', '.txt']:
                    continue
                print(index, file)

                log_file_path = file.path
                logging.info(f'Found log file: {log_file_path}')
                # break       
            print("-------")
```

The result for an incorrect process is this:
```
-------
46 popenfile(path='C:\\Users\\Ian\\Desktop\\Plot Manager\\manager.log', fd=-1)
62 popenfile(path='C:\\Users\\Ian\\Desktop\\Plot Manager\\log\\evo_2021-05-05_09_07_47_812232.log', fd=-1)
-------
```
If the `break` is still there, the loop encounters `manager.log` first on the 46th index and uses that as the `log_file_path` instead of the correct path for the log in the 62nd index.

**Comment by swar** [comment]
Got it. Very good in-depth explanation as well!

**Pull request merged**
