### PR TITLE
chinese translation

### PR DESCRIPTION
**Pull request by pkwenda**

### CODE REVIEW

**Comment by swar** [comment]
@pkwenda If I need your help updating are you able to help out? The development branch actually has a lot more information that I added which I am testing out locally

**Comment by pkwenda** [comment]
Yes, I've thought about it. I'll help @swar

**Comment by swar** [comment]
> Yes I'll help @swar

Thank you :)

I will have the development version up sometime this weekend

**Comment by StormYudi** [comment]
我亦来自中国，但是恕我直言，您提交的翻译颇有机器翻译的味道。
诸如：**你希望保持为真**。如果翻译为：**推荐保持为真**，是否更符合中文的语境？
亦或者：我更喜欢venv，**因为它是一个标准**。如果翻译为：我更喜欢venv，**因为这是标准化的**，是否更好？
请考虑修改您的翻译
@pkwenda

**Comment by swar** [comment]
> 我亦来自中国，但是恕我直言，您提交的翻译颇有机器翻译的味道。
> 诸如：**你希望保持为真**。如果翻译为：**推荐保持为真**，是否更符合中文的语境？
> 亦或者：我更喜欢venv，**因为它是一个标准**。如果翻译为：我更喜欢venv，**因为这是标准化的**，是否更好？
> 请考虑修改您的翻译
> @pkwenda

I'm not sure if you can understand me, but I would like to get more opinions from people who speak the language before I merge this into the library. Your comments create concern in me because I am unsure if this translation helps.

**Comment by StormYudi** [comment]
@swar Thank you. But his translation is like copying all the English README files to Google Translate and then translating them into Chinese. There are many things that cannot be understood in the Chinese context.

**Comment by swar** [comment]
Thank you @StormYudi. I will wait to see if there is more input from people prior to merging it.

**Comment by pkwenda** [comment]
看了你的意见，首先我不是翻译大师，我仅凭对开源社区的热爱，我多年工作习惯对于要求时间很紧迫的文件翻译先进行机翻，我使用 DeepL ，然后校对两遍写个初版：
- 一遍是文字格式同步原作
- 一遍通读是否合理通顺

再提交之后我也进行了多次调整，昨晚我答应了作者长期更新的请求，相信会有更多的地方会在以后变得更好，但不是 1 个小时能做到的。
但是我不理解的是：你在哪里看到 「你希望保持为真」？或者说我的文档哪里有「真」？我明明在凌晨 6 点之前修改过了
在我录制宣传完这个开源库（他很酷）已经凌晨 6 点了，现在我刚刚起床。
Anyway 我会撤回这个 PR ，仅供我的朋友们观看，期待你给它提供完美的翻译 🤝 @swar 

=== 

sorry, what do u mean :  “ like copying all the English README files to Google Translate ？”  
Fuck, this is my Over 60 minutes of effort

Anyway, good luck

**Comment by pkwenda** [comment]
> @swar Thank you. But his translation is like copying all the English README files to Google Translate and then translating them into Chinese. There are many things that cannot be understood in the Chinese context.

 看了你的意见，首先我不是翻译大师，我仅凭对开源社区的热爱，我多年工作习惯对于要求时间很紧迫的文件翻译先进行机翻，我使用 DeepL ，然后校对两遍写个初版：
- 一遍是文字格式同步原作
- 一遍通读是否合理通顺

再提交之后我也进行了多次调整，昨晚我答应了作者长期更新的请求，相信会有更多的地方会在以后变得更好，但不是 1 个小时能做到的。
但是我不理解的是：你在哪里看到 「你希望保持为真」？或者说我的文档哪里有「真」？我明明在凌晨 6 点之前修改过了
在我录制宣传完这个开源库（他很酷）已经凌晨 6 点了，现在我刚刚起床。
Anyway 我会撤回这个 PR ，仅供我的朋友们观看，期待你给它提供完美的翻译 🤝  

=== 

sorry, what do u mean:  “ like copying all the English README files to Google Translate ？”  
Fuck, this is my Over 60 minutes of effort, ok ok, I close this PR

Anyway, good luck


================

I've popularized this tool on youtube ，10 hours have been watched by 2000 people，and this is what I can do for you @swar

**Comment by swar** [comment]
I'm reopening this PR to get more feedback from the community which is what I was waiting for in the first place. I do not understand anything going on in the README so it is best for me to wait for community input.

> I've popularized this tool on youtube ，10 hours have been watched by 2000 people，and this is what I can do for you @swar

I understand your frustrations, but I do not do anything for views, fame, or anything of that nature. I simply like the Chia project which is why this tool was created. In all fairness, there's already over five separate videos on this tool in four different languages including yours. It serves a much desired purpose and benefits the community and I am sure it benefits you with bringing more views to your channel for people wanting to plot more efficiently.

**Comment by pkwenda** [comment]
Because my translation is more arbitrary, Easier to understand, and change file dir, so it may not be suitable for the official language
I do not  for views, fame, or anything of that nature too
Maybe the friend above will give you a good translation
sorry @swar

**Comment by swar** [comment]
@pkwenda  I do not see why we could not have waited for more opinions from the community before deciding to close this pull request. In the end, it's your work so you have control over what you want to do with it.

**Comment by FreedomForGIthub** [comment]
I'm from Hong Kong, China ,Not at all as bad as @StormYudi  said，and I really don't understand why he said that, I think pkwendd's translation is perfectly understandable and getting better now, which I have to say is a shame
@swar

**Comment by swar** [comment]
> I'm from Hong Kong, China ,Not at all as bad as @StormYudi said，and I really don't understand why he said that, I think pkwendd's translation is perfectly understandable and getting better now, which I have to say is a shame
> @swar

Thank you. Unfortunately the pull request was closed by @pkwenda so I am unable to add it back even if I wanted too. 😞

**Comment by StormYudi** [comment]
I made my opinion because I saw that the changes he submitted **at that time** did indeed have translations that did not fit the Chinese context, but I later saw that he later submitted further good translations, but unfortunately he has closed this PR.
I didn't mean to offend him, I just hope that our translation work can be performed perfectly.

**Comment by StormYudi** [comment]
From his reply, I can read that he cannot accept different opinions, does not make rational thinking and shows a bad attitude. This is a very bad thing. But as you said, the decision is in his hands.

**Pull request closed without merging**
