### PR TITLE
Check for Prometheus running in manager state

### PR DESCRIPTION
**Pull request by iwex**

### CODE REVIEW

**Comment by iwex** [comment]
Not working :smile:

**Comment by iwex** [comment]
Tried to fix, and now seem like it's working

**Comment by salsaly4** [comment]
You still not stopping server on exit, that's not right. You should add global like `PROMETHEUS_SERVER = start_http_server(port)` and on add

`PROMETHEUS_SERVER.shutdown()
PROMETHEUS_SERVER.stop()`

on `manager stop` command

**Comment by salsaly4** [comment]
Sorry for previous comment, found that the problem was in prometheus-client exposition implementation.

Is it simpler to check for socket like this:

```
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
if sock.bind(('127.0.0.1', port)):
    sock.close()
    start_http_server(port)
```

**Comment by salsaly4** [comment]
Or even more simpler:

```
try:
    start_http_server(port)
except:
    pass
```

**Comment by creamsoup** [comment]
the prometheus client should be only running by manager daemon. other commands like view, json etc shoulnd't even start prometheus client. if two manager.py with same config is running, this is legit error. so, skipping exception or port being used is not the best solution. seems global is the better solution but global is bad. 
I solved this in #824 (pretty much same idea). please comment in the PR if you don't agree.

**Pull request closed without merging**
