### PR TITLE
Update plots.py

### PR DESCRIPTION
**Pull request by Ganbin**
change pool public key from -p to -c to be able to be compliant with the new pool protocol

### CODE REVIEW

**Comment by Ganbin** [comment]
I have seen other pull requests that add a new key for this but I think that only changing the previous pool_key (-p) by the new one(-c) would work. I don't know really know what is the use of the old -p one and if anybody would combine those 2.

**Comment by ycatlive** [comment]
can anyone confirm if this will work? i think the CLI plotting comments in 1.2.0 changed to "chia plotnft" instead of "chia plots create"

**Comment by ycatlive** [comment]
i think they changed the CLI to "chia plotnft create" instead of "Chia plot create" so simple change p to c may not be working?

**Comment by Ganbin** [comment]
No, the chia `chia plotnft create` is to create a singleton plot that is used to pool. But the way to create plot is still the same as before, only to change -p by -c.

See the doc here https://github.com/Chia-Network/chia-blockchain/wiki/Pooling-User-Guide#command-line-interface

**Comment by CakeRepository** [comment]
Have you tested this yet?

**Comment by TomasVelPar** [comment]
check this [https://github.com/swar/Swar-Chia-Plot-Manager/pull/1224](https://github.com/swar/Swar-Chia-Plot-Manager/pull/1224), and make you the modifications in the code

**Comment by jack60612** [comment]
@Ganbin new pool support was added
Please close your pull request

**Comment by swar** [comment]
Already added another implementation of this

**Pull request closed without merging**
