### PR TITLE
Adding Telegram Notifications

### PR DESCRIPTION
**Pull request by swar**

### CODE REVIEW

**Comment by fiveangle** [comment]
This should be rolled back until it works.  Telegram api requires the chat id or there's no way to route the alert.

**Comment by swar** [comment]
> This should be rolled back until it works. Telegram api requires the chat id or there's no way to route the alert.

It's already in and doesn't hurt anyone using it right now. I'm not going to spend the time to make a new version to just remove it to add it back in on another release.

**Comment by fiveangle** [comment]
if it isn't messing anything up, i see your point.  luckily there are fixes already submitted by others

**Comment by millstone98** [comment]
@fiveangle where can I find the fixes?

**Comment by fiveangle** [comment]
There is no fix that i am aware of.

**Pull request merged**
