### PR TITLE
estestimate overall time for plot processes to finish

### PR DESCRIPTION
**Pull request by hgdubbe**
estimates how long a plot will take at all based on progress and elapsed time.

ugly code but works quite well ;)

### CODE REVIEW

**Comment by creamsoup** [comment]
hmm interesting. we could learn better estimation from previous job's process (using job's name). 
just using percentage can be off by a lot depends on configuration. e.g. 1thread vs 4 threads phase 1 takes very different amount time and doesn't really affect other phases.  i am wondering showing this estimate is better or not. i guess @swar will answer.

**Comment by DilatoryCheetah** [comment]
I think time estimates will vary a lot based on system load.  What would be more useful would be to present progress as 2 numbers:

phase% / total%

So when you are in phase 1 you would see 92.94 / 31.67 or something like that.  So you know about how much more you have to go on the current phase

**Comment by hgdubbe** [comment]
well you got to run manager.py analyze_plots and put in the right numbers in your config after you ran enough jobs to get a reliable average for for the percentages for your current configuration (you need to get rid of logs with older config of course before doing so). its pretty accurate for me as soon as progress passes like 10%.

if someone knows how to fix the spacing for the tables with ansichars feel free to do so ;)

**Comment by hgdubbe** [comment]
has become more of a mod than a pull request by now

**Pull request closed without merging**
