### PR TITLE
Additional parameters for madmax backend

### PR DESCRIPTION
**Pull request by w4d3j**
Added -v and -K parameters for madmax chia_plot executable.  

-v = # threads for phases 3&4
-K = thread multiplier for phase 2

### CODE REVIEW

**Comment by swar** [comment]
Added a question about how you're loading it into job configs

**Comment by w4d3j** [comment]
Not sure exactly what you mean.  I added the parameters in jobs.py, objects.py, and plots.py (also default config), and they're getting passed to chia_plot just fine along with the others.

**Comment by swar** [comment]
@w4d3j 

These lines should be the below instead of the one above.

```python
job.threadX_p2 = info['threadX_p2']
job.threadX_p2 = info.get('threadX_p2')
```

If we don't use .get() in the dictionary to grab the value, then it will be a breaking change for everyone with an older config file.

**Comment by w4d3j** [comment]
Thank you for your time and energy showing me how to improve.  I've added the .get() method.  

I noticed other places using .get() specified a second parameter for the method even when it was None, and I considered doing it to fall in line with the rest of the method calls but decided to ask a question first:

If .get() returns None if the key is not found and there is no second argument, why the redundancy of specifying None as the second argument?  Is it for readability?  Or perhaps backwards-compatibility?

**Review by swar — COMMENTED** [review]
> Thank you for your time and energy showing me how to improve. I've added the .get() method.
> 
> I noticed other places using .get() specified a second parameter for the method even when it was None, and I considered doing it to fall in line with the rest of the method calls but decided to ask a question first:
> 
> If .get() returns None if the key is not found and there is no second argument, why the redundancy of specifying None as the second argument? Is it for readability? Or perhaps backwards-compatibility?

No worries, I always like helping out with this kind of stuff.

In this case, it's honestly just redundant and not necessary. Sometimes when I have to keep track of a lot of things, it helps to see that it will return None, or in this case will help other developers know that having a None value is okay as it is not required.

If it's there or not, it would not matter :)

**Pull request merged**
