### PR TITLE
New official pool support / nftpool support

### PR DESCRIPTION
**Pull request by jack60612**
The new pool_url variable allows the use of  Pool Contract Address 
Refer to 
https://github.com/Chia-Network/chia-blockchain/wiki/Pooling-FAQ#how-do-i-assign-portable-plots-to-a-pool

Tested and working on linux and windows

### CODE REVIEW

**Comment by jack60612** [comment]
@swar

**Comment by mladenperisic** [comment]
@jack60612 Hey, Jack! I like this PR! How about you merge this PR https://github.com/swar/Swar-Chia-Plot-Manager/pull/1139/files from @jchristman75 in your fork?

**Comment by jack60612** [comment]
@mladenperisic i do understand where you are coming from. however i would like to get this fork merged as soon as possible so i'm probably not going to do that

**Comment by TomasVelPar** [comment]
@jack60612 thank you so much. I have made those modifications to the original code and its working for me.

**Comment by adobito** [comment]
@jack60612 I tried running your branch and was having super weird issues that I had to debug. I kept my `pool_public_key` in the `config.yaml` and just added my `pool_url` but it didn't seem to be working. After debugging, I found out the the process exits/dies with this error 
```RuntimeError: Choose one of pool_contract_address and pool_public_key```
 but it hangs as a defunct process, so Swar sees the PID still running and it causes weird behavior. Swar gives 0 feedback right now on this and I think most people would not be able to debug this on their own if they ran into the same issue.

**Comment by TomasVelPar** [comment]
I think you must delete (or comment) your pool_public_key, and is not the pool url, its your pool contract address (you can obtaint it making a plot with chia gui, deleting it after few seconds and checking que plot log).


> @jack60612 I tried running your branch and was having super weird issues that I had to debug. I kept my `pool_public_key` in the `config.yaml` and just added my `pool_url` but it didn't seem to be working. After debugging, I found out the the process exits/dies with this error
> `RuntimeError: Choose one of pool_contract_address and pool_public_key`
> but it hangs as a defunct process, so Swar sees the PID still running and it causes weird behavior. Swar gives 0 feedback right now on this and I think most people would not be able to debug this on their own if they ran into the same issue.

**Comment by adobito** [comment]
> 
> 
> I think you must delete (or comment) your pool_public_key, and is not the pool url, its your pool contract address (you can obtaint it making a plot with chia gui, deleting it after few seconds and checking que plot log).
> 
> > @jack60612 I tried running your branch and was having super weird issues that I had to debug. I kept my `pool_public_key` in the `config.yaml` and just added my `pool_url` but it didn't seem to be working. After debugging, I found out the the process exits/dies with this error
> > `RuntimeError: Choose one of pool_contract_address and pool_public_key`
> > but it hangs as a defunct process, so Swar sees the PID still running and it causes weird behavior. Swar gives 0 feedback right now on this and I think most people would not be able to debug this on their own if they ran into the same issue.

The point I was trying to make is that this is a problem and the plot manager should catch this.

**Comment by jack60612** [comment]
> I think you must delete (or comment) your pool_public_key, and is not the pool url, its your pool contract address (you can obtaint it making a plot with chia gui, deleting it after few seconds and checking que plot log).
> 
> > @jack60612 I tried running your branch and was having super weird issues that I had to debug. I kept my `pool_public_key` in the `config.yaml` and just added my `pool_url` but it didn't seem to be working. After debugging, I found out the the process exits/dies with this error
> > `RuntimeError: Choose one of pool_contract_address and pool_public_key`
> > but it hangs as a defunct process, so Swar sees the PID still running and it causes weird behavior. Swar gives 0 feedback right now on this and I think most people would not be able to debug this on their own if they ran into the same issue.

yep i made this code 10 days ago before this was clear so im  fixing it now

**Comment by 125devin** [comment]
Is it necessary to keep the 'pool_public_key' variable? Is the '-p' flag needed for anything? 

Would changing one letter in the file pools.py do the trick for updating to chia 1.2 pools?

    flags['p'] = pool_public_key
to
    flags['c'] = pool_public_key

Would the pool_public_key variable in the config.yaml file then work for the new "pool contract key"?

**Comment by jack60612** [comment]
> Is it necessary to keep the 'pool_public_key' variable? Is the '-p' flag needed for anything?
> 
> Would changing one letter in the file pools.py do the trick for updating to chia 1.2 pools?
> 
> ```
>     flags['p'] = pool_public_key
> ```
> 
> to
> flags['c'] = pool_public_key
> 
> Would the pool_public_key variable in the config.yaml file then work for the new "pool contract key"?

Backwards compatibility
If swar wants he can remove it but i dont think its my place to

**Comment by swar** [comment]
@jack60612 can you add a placeholder to the Russian README as well and I will get this merged out soon

**Comment by jack60612** [comment]
> @jack60612 can you add a placeholder to the Russian README as well and I will get this merged out soon

added

**Comment by 125devin** [comment]
If both the '-p' and '-c' flags are used, then 'chia plots create' gives an error saying to choose one or the other.

RuntimeError: Choose one of pool_contract_address and pool_public_key

I think chia 1.2 generates the old non-pooling type of plots if no pool contract key is specified with '-c'

**Pull request merged**
