### PR TITLE
Add exclude_final_dir option for jobs

### PR DESCRIPTION
**Pull request by Acaki**
Add ability to specify `-x` for `chia plots create`
Useful when you're plotting to a network drive, that has its own harvester running  

螢幕擷取畫面 2021-04-30 173801

### CODE REVIEW

**Comment by swar** [comment]
This is great @Acaki 

My only request is can you change "dir" to "directory" so it stays consistent with the other places I am using directory? Nice work!

**Comment by swar** [comment]
Oh also you'll want to add that value to the Job object as well

https://github.com/swar/Swar-Chia-Plot-Manager/blob/main/plotmanager/library/utilities/objects.py

**Comment by cdgraff** [comment]
Hi @swar I'm searching for the same feature, can merge please? thanks!

**Comment by daryledesilva** [comment]
right now I'm using this fork because of this feature too. hoping this gets
merged soon!

**Comment by swar** [comment]
Sorry everyone, it's been a very busy week in terms of keeping up with questions and then getting some time to dedicate to making changes.

**Pull request merged**
